export default {
  "login": "PatrickAlphaC",
  "id": 54278053,
  "node_id": "MDQ6VXNlcjU0Mjc4MDUz",
  "avatar_url": "https://avatars.githubusercontent.com/u/54278053?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/PatrickAlphaC",
  "html_url": "https://github.com/PatrickAlphaC",
  "followers_url": "https://api.github.com/users/PatrickAlphaC/followers",
  "following_url": "https://api.github.com/users/PatrickAlphaC/following{/other_user}",
  "gists_url": "https://api.github.com/users/PatrickAlphaC/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/PatrickAlphaC/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/PatrickAlphaC/subscriptions",
  "organizations_url": "https://api.github.com/users/PatrickAlphaC/orgs",
  "repos_url": "https://api.github.com/users/PatrickAlphaC/repos",
  "events_url": "https://api.github.com/users/PatrickAlphaC/events{/privacy}",
  "received_events_url": "https://api.github.com/users/PatrickAlphaC/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Patrick Collins",
  "company": "Working on Chainlink",
  "blog": "https://www.youtube.com/c/patrickcollins",
  "location": "Boston",
  "email": null,
  "hireable": null,
  "bio": "Developer Advocate on the Chainlink protocol.\r\n\r\nFounder and CEO of Alpha Chain.",
  "twitter_username": "patrickalphac",
  "public_repos": 210,
  "public_gists": 72,
  "followers": 4621,
  "following": 31,
  "created_at": "2019-08-19T14:13:41Z",
  "updated_at": "2022-08-11T13:43:39Z"
}